# Generated by Django 4.2.8 on 2024-01-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_facebook_url_profile_fb_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fb_url',
        ),
    ]
