# Generated by Django 4.2.8 on 2024-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
