# Generated by Django 4.2.8 on 2024-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
